import json

with open('notebooks/EMNIST_to_Gambo.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

md_cell = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 8. Balancing: Pangkas EMNIST Berlebih\n",
        "\n",
        "Normal terlalu banyak. Kita hapus file EMNIST yang berlebih agar rasio Normal:Dyslexia mendekati 1:1.\n",
        "Strategi: hapus dari huruf yang jumlahnya paling banyak terlebih dahulu."
    ]
}

code_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "import os, re, random\n",
        "from collections import defaultdict\n",
        "\n",
        "random.seed(42)\n",
        "\n",
        "BASE = 'Dataset'\n",
        "TRAIN_N = os.path.join(BASE, 'Gambo_EMNIST', 'Train', 'Normal')\n",
        "TEST_N = os.path.join(BASE, 'Gambo_EMNIST', 'Test', 'Normal')\n",
        "\n",
        "# Hitung total Dyslexia\n",
        "train_corr = len(os.listdir(os.path.join(BASE, 'Gambo_EMNIST', 'Train', 'Corrected')))\n",
        "train_rev = len(os.listdir(os.path.join(BASE, 'Gambo_EMNIST', 'Train', 'Reversal')))\n",
        "test_corr = len(os.listdir(os.path.join(BASE, 'Gambo_EMNIST', 'Test', 'Corrected')))\n",
        "test_rev = len(os.listdir(os.path.join(BASE, 'Gambo_EMNIST', 'Test', 'Reversal')))\n",
        "total_dyslexia = train_corr + train_rev + test_corr + test_rev\n",
        "\n",
        "total_normal_now = len(os.listdir(TRAIN_N)) + len(os.listdir(TEST_N))\n",
        "to_remove = total_normal_now - total_dyslexia\n",
        "\n",
        "print(f'Normal saat ini:  {total_normal_now:,}')\n",
        "print(f'Dyslexia target:  {total_dyslexia:,}')\n",
        "print(f'Harus dihapus:    {to_remove:,} file Normal')\n",
        "\n",
        "if to_remove <= 0:\n",
        "    print('Sudah seimbang. Tidak perlu hapus.')\n",
        "else:\n",
        "    # Kumpulkan file EMNIST (format: Huruf-index.png)\n",
        "    # File Gambo asli pakai underscore (d_3620.png)\n",
        "    emnist_files = []\n",
        "    for folder in [TRAIN_N, TEST_N]:\n",
        "        for f in os.listdir(folder):\n",
        "            m = re.match(r'^([A-Za-z])-(\\d+)\\.png$', f)\n",
        "            if m:\n",
        "                letter = m.group(1)\n",
        "                idx = int(m.group(2))\n",
        "                emnist_files.append((os.path.join(folder, f), letter, idx))\n",
        "\n",
        "    print(f'Total file EMNIST terdeteksi: {len(emnist_files):,}')\n",
        "\n",
        "    # Hitung per huruf\n",
        "    letter_counts = defaultdict(list)\n",
        "    for path, letter, idx in emnist_files:\n",
        "        letter_counts[letter].append((path, idx))\n",
        "\n",
        "    sorted_letters = sorted(letter_counts.keys(),\n",
        "                            key=lambda l: len(letter_counts[l]), reverse=True)\n",
        "\n",
        "    print('\\nDistribusi per huruf (top 10):')\n",
        "    for l in sorted_letters[:10]:\n",
        "        print(f'  {l}: {len(letter_counts[l]):,}')\n",
        "\n",
        "    # Binary search cap per huruf\n",
        "    total_emnist = len(emnist_files)\n",
        "    target_emnist = total_emnist - to_remove\n",
        "\n",
        "    lo, hi = 0, max(len(letter_counts[l]) for l in sorted_letters)\n",
        "    while lo < hi:\n",
        "        mid = (lo + hi) // 2\n",
        "        kept = sum(min(len(letter_counts[l]), mid) for l in sorted_letters)\n",
        "        if kept < target_emnist:\n",
        "            lo = mid + 1\n",
        "        else:\n",
        "            hi = mid\n",
        "    cap = lo\n",
        "\n",
        "    print(f'\\nCap per huruf: {cap}')\n",
        "    print(f'Target EMNIST dipertahankan: {target_emnist:,}')\n",
        "\n",
        "    # Hapus file melebihi cap (index terbesar dihapus duluan)\n",
        "    deleted = 0\n",
        "    for letter in sorted_letters:\n",
        "        files_for_letter = letter_counts[letter]\n",
        "        if len(files_for_letter) <= cap:\n",
        "            continue\n",
        "        files_for_letter.sort(key=lambda x: x[1], reverse=True)\n",
        "        excess = files_for_letter[:len(files_for_letter) - cap]\n",
        "        for path, idx in excess:\n",
        "            os.remove(path)\n",
        "            deleted += 1\n",
        "        print(f'  {letter}: {len(files_for_letter):,} -> {cap} (hapus {len(excess)})')\n",
        "\n",
        "    print(f'\\nTotal file dihapus: {deleted:,}')\n",
        "\n",
        "    # Verifikasi\n",
        "    final_train = len(os.listdir(TRAIN_N))\n",
        "    final_test = len(os.listdir(TEST_N))\n",
        "    final_normal = final_train + final_test\n",
        "\n",
        "    print(f'\\n--- Hasil Akhir ---')\n",
        "    print(f'Train/Normal: {final_train:,}')\n",
        "    print(f'Test/Normal:  {final_test:,}')\n",
        "    print(f'Total Normal: {final_normal:,}')\n",
        "    print(f'Total Dyslexia: {total_dyslexia:,}')\n",
        "    ratio = total_dyslexia / final_normal if final_normal > 0 else 0\n",
        "    print(f'Rasio Normal:Dyslexia = 1:{ratio:.2f}')"
    ]
}

nb['cells'].extend([md_cell, code_cell])

with open('notebooks/EMNIST_to_Gambo.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
print('Cell balancing berhasil ditambahkan.')
